summary: Upload a file.
operationId: postFile
consumes:
  - multipart/form-data
produces:
  - application/json
parameters:
  - in: formData
    name: file 
    description: "Accepts a input file"
    required: true
    type: file
    description: The file to upload
responses:
    200:
      description: upload succseful
    400:
      description: upload Error
    404:
      description: Fatal Error

